spring.application.name=ligafacil

spring.datasource.url=jdbc:postgresql://localhost:5432/ligafacil
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect